### ISSUE TITLE
HoDoKu base

### ISSUE THREAD

**Issue by 1to9only** [1to9only/HoDoKu-Discuss#1]
Initial discussions.
I intend to create a new HoDoKu repository in GitHub for the intended changes.

1. The code base can be the tagged [r117] Release 2.2.0.
hobiwan last change was on 2013-09-06 related to [r147] Tabling new, work in progress...
yoki123 last commit was on 29 Dec 2017.
Pseudofish last commit was 24 Jan 2020.
[Edit] Development on the 3 projects appear stopped. I would prefer to use the most recent code base (Pseudofish's), and move this along a little bit (maybe for others to continue developing); rather than create and leave another version/release hanging.

2. Are there any source code changes to your 2.2.1 version?
If available, I'll try to build a 2.2.1 version before making any changes.
[Edit] Modifying the HoDoKu_221.jar is possible, but modifications will be easier if it's source code were available.

**Comment by CCV54** [comment]
Hi @1to9only, many thanks!

I believe I do have the relevant source code. Even though it is numbered 147, it is not the same as hobiwan's r147.
[hodoku-code-147.zip](https://github.com/1to9only/HoDoKu-Discuss/files/5235649/hodoku-code-147.zip)
I can see my image work in there, from two years ago, which I have since further refined.

And, yes, "filter" colour refers to PseudoFish's version. In 2.2.0 it comes under Background/ALS, on Colors tab. The value 200:221:227 applies to "Possible:" There I've changed Forbidden: to 242:188:185 and (I think) Selection: to 255:255:150 as well. Both Normal: and Altern.:  I have at 245:245:255. I'd forgotten about those, but, please, would you add them to the list.

Btw, I had this version labelled as 2.2.1 and I'd like to keep it that way. It has no relation to PseudoFish's 2.2.1.

Regards,

Colin.

**Comment by CCV54** [comment]
One more thing, sorry, I keep forgetting. Colour for Values: 0:102:102.

**Comment by CCV54** [comment]
As for forking from PseudoFish's code base, I can see a couple of problems.
One thing bothering a few people is that the normal approach to colouring cells or candidates no longer functions (as it did in 2.2.0). Under Options menu, you could select "Color Cells" or "Color Candidates" and the chosen option would be displayed next to the colour bar - bottom left. Now it's stuck on "Coloring: none", and while the mouse pointer appears to pick up a chosen Pen colour it doesn't apply the colour anywhere.  I suspect that's a probably unintended result of changes he made to Active Cell view. Probably something to take up with him as well...

Under Help, Report error... links to https://sourceforge.net/p/hodoku/bugs-and-feature-requests/ which is how I found out about his project. Similarly for Ask a question...

And, you did ask, "Are there any source code changes to your 2.2.1 version?" Not sure what you mean, but it does have Confirmation dialogue added for Create a new sudoku (except when only easy steps [singles} are present) and Concrete Hint for XYZ-Wing displays three candidates (instead of two as in 2.20) and the bug in ColorKu colour selection pane is fixed.

**Comment by 1to9only** [comment]
The question about your 2.2.1 version, rephrased, is: Do you have the java source code which your 2.2.1 version is built from? Including the the Confirmation, XYZ-Wing and ColorKu changes.

I'll first attempt to build your 2.2.1 version from source, and make changes thereafter.

It would be good if you had the source code (I can make changes straight away!), otherwise I'll decompile your 2.2.1 classes, compare these against the source code for the 2.2.0 release, and arrive at the 2.2.1 source code. This will take some time. I'll be doing this when my spare time permits.

My (preferred) starting HoDoKu code base would (then) be [r117] Release 2.2.0.

Hobiwan has made lots of changes to [r147] Tabling new, work in progress..., so anything between [r117] and [r147] will be unfinished/unreleased code!

Some of your changes are already in [r147] - this is OK, as I can do cross-reference checks when recreating the 2.2.1 source.

The filter color stuff can be copied from Pseudofish's version.

So this is (currently) how I would tackle this project:
- for 2.2.0:
- create my HoDoKu repository on GitHub
- update the source code of hobiwan's 2.2.0 release
- there are some changes needed so I can compile with no warning errors
- build and release 2.2.0 (this will/should be the same as hobiwan's 2.2.0)
- for 2.2.1:
- update the source code to your 2.2.1 version
- build and release 2.2.1 (this will/should be the same as your 2.2.1 version)

FWIW: There are a number of HoDoKu projects uploaded on GitHub, even one with Chinese translations: https://github.com/zh3305/HoDoKu

PS. I use HoDoKu only occasionally, and I am aware that you are very active over at the sourceforge HoDoKu site, and that hobiwan still visits there.

PPS. I use SudokuExplainer more, and have modified the SE source quite a lot to create solvers for other sudoku types: 6x6, 16x16, etc. There is also a SukakuExplainer that will work with sukakus (pencilmarks sudoku) and other variants: Latin Square, X, Windoku, Asterisk, etc: https://github.com/SudokuMonster/SukakuExplainer. For historical reasons, I also maintain my own version of SukakuExplainer that does not do variants.

**Comment by 1to9only** [comment]
From a preliminary scan:
- 2.2.0 has 246 files
- 2.2.1 has 2 additional files (f_xyc_inactive.png, inactive.png)
- in 2.2.1: 86 files differ from 2.2.0 (this includes the 19 filter png's (in Sudoku_Filter.zip))

Some of the file differences appear trivial (the decompiler produced slightly different 2.2.0 and 2.2.1 files), but the tedious (boring!) work is examining all the files that differ to work out what makes up the 2.2.1 code.

As noted earlier, if you have the 2.2.1 source code, it will save me time. Otherwise, it's not a big issue with me. I think you've been asking for changes to HoDoKu for some time! You'll just have to wait some more!!

**Comment by CCV54** [comment]
My apologies,
The source code for my 2.2.1, I believe, is this 
[hodoku-code-r147.zip](https://github.com/1to9only/HoDoKu-Discuss/files/5242378/hodoku-code-r147.zip). If it's not, then, sorry, I can't help you.

I did make a f_xyc_inactive.png, but it isn't required at all, The inactive.png appears to be for ColorKu filter bar.

**Comment by 1to9only** [comment]
hodoku-code-r147.zip (from the file size alone) appears to be the most recent code from sourceforge. I'll be using this for reference only, to pick out code that are in 2.2.1.

As I noted earlier, I intend to start from the 2.2.0 source code, update this to 2.2.1, before making any new changes. The work I outlined to recreate the 2.2.1 source is chugging along, I'll document what I've found later. 

PS. I noticed Bernhard Hobiger as the 'Owner' of some recent 'Bugs and Feature Requests' - I took this as a sign that he still visited the sourceforge web site!!

**Comment by 1to9only** [comment]
I've created https://github.com/1to9only/hobiwan-s-HoDoKu - it is cloned from https://svn.code.sf.net/p/hodoku/code/HoDoKu/trunk - This is for reference only.

**Comment by CCV54** [comment]
The hodoku-code-147.zip I sent isn't the same as hobiwan's _r_147. I can see some of my image work in there, from two years ago...
It should contain the XYZ-Wing Concrete Hint change and the bug fix for ColorKu colour selection panel too, and the confirmation dialogue on Create new sudoku which is disabled when singles only are present. I guess that's what you mean by the code that's in 2.2.1. Best I can do anyway.

As for Bernhard being the "owner" of any such, that's an option presented when creating a new ticket - to nominate him as owner. Cheers.

**Comment by 1to9only** [comment]
Yes. I've had a quick browse of the 2 hodoku source code you posted. My view is that they do not contain the full 2.2.1 source. I can see some of the changes in Feb/Mar 2018 - I'll use them for reference.
I think the 2018 changes are pre 2.2.1 - as I can see only one "Create a new Sudoku." confirm dialog, whereas the decompiled 2.2.1 shows checks for game started and sudoku not completed.

@CCV54 
I don't use Hodoku much, and I don't have a feel of Hodoku's history around 2012/3 - but I'm curious to know why you dont want to use hobiban's 2.3.0 beta [r147] code, slap on your changes to end up with a 2.3.1 version?
I'm guessing that hobiwan's 2.3.0 work on the Table Solver is incomplete, breaks some 2.2.0 stuff, and so is not quite useful!

Currently, I'm still planning to use hobiwan's 2.2.0 to build up to your 2.2.1.

**Comment by CCV54** [comment]
@1to9only there was a  2.3.0_beta.jar file available, but I can't locate it now. I happen to know it had a serious bug in the Look & Feel startup options. It always opened with Metal, no matter what.

Nonetheless, I was under the impression that my 2.2.1 was built upon hobiwan's r147 code. ?
And, yes, you are correct. The code I provided does not reflect all the changes made. I can see changes made up to March 2018, whereas the project was not completed until May 2018. I've contacted the producers of it, to see if they can still send me the proper source code. Will have to wait and see... They already wasted a lot of my time and money by hooking the beta version in the first place. :\

**Comment by 1to9only** [comment]
I'm pretty certain that your 2.2.1 is built atop hobiwan's 2.2.0.
I've decompiled (reverse-engineered!) hobiwan's 2.2.0.jar and your 2.2.1.jar , and have an idea of what's changed.

Some changes are in the March 2018 code, and I can lift these asis:
- ColorKu inactive image filter, and buttons 3/4/5 fix for selection panel.
For the other changes, I can replicate them from the decompiled 2.2.1 stuff.
- Confirm when Create a new Sudoku
- 3 candidates XYZ-Wing fix
There are also lots of Color changes, but I've not sifted through these yet!

I probably don't need the May 2018 changes - would be nice to have them if available. My own view is that the developers will delay providing (misplace!) the May 2018 source code, to protect their revenue stream!!

**Comment by CCV54** [comment]
Yeah, it is built upon hobiwan's 2.2.0.jar. The next .jar version available being the 2.3.0 beta I mentioned. Don't know how the source code came back as "147"...

I must concur with your view of what the developers will likely do. As it is, they demand hiring them for 10 hour blocks for even the slightest thing.

The total number colour changes, I couldn't tell you either. I've been tweaking them for a couple of years. Why I want them, especially ColorKu, changed now is to suit more default brightness:contrast settings. Mine were a bit peculiar, at the time.

Once again, I must express my appreciation for your interest in and your efforts toward this project. Thank you, thank you, thank you!

**Comment by CCV54** [comment]
P.S.
Look&Feel, I believe is something to do with Java Swing - not something you can code for. Still.. There's a problem in CDE/Motif in that much of the text on the status bar is black on black. Plus, I had an idea to make the mouse-click effect on Metal filter bar slightly less ordinary. Somewhat reflecting the mouse-over effect, but in reverse. Not quite satisfactory results as yet, but might consider it a little further.

**Comment by 1to9only** [comment]
I've now created: https://github.com/1to9only/HoDoKu
It's hobiwan's HoDoKu rolled back to 2.2.0 - I'll be making changes to this.
I'll copy text from this Issue to other Issues as and when needed.
Remember, I'll be deleting HoDoKu-Discuss about 1 week after I release 2.2.2. To keep a copy of discussions, copy & paste text into a file. Or if using a chrome-based browser, print this and save as a pdf file.
Issue closed.
