### ISSUE TITLE
The End

### ISSUE THREAD

**Issue by 1to9only** [1to9only/HoDoKu-Discuss#6]
Hodoku 2.2.2 has been released. In 2-3 days, these discussions will be deleted!

I'll be less active on this HoDoKu, maybe I'll make some custom changes for personal use, or likely borrow code from other Hodokus on GitHub for personal use. Other Hodoku users will be able to copy/fork this Hodoku, some may even offer snippets of code, fixes, features, etc.

@CCV54,
You can then either:
- **make** a copy of my HoDoKu into your own repository. Your copy of HodoKu will be separate from my own Hodoku, and in future you'll be able to make your own changes to your Hodoku.
- **fork** a copy of my HoDoKu into your own repository. This is how open-source projects work. Your copy of HodoKu (your master) will be linked from my own Hodoku (my master/upstream), you (and other developers) will raise an issue, fork the repository, create a branch to develop a fix or new code, then do a pull request to have it merge into the master/upstream repository. [The terminology of the Git stuff can be a bit confusing!]

**To make a copy of my HoDoKu into your own repository**:
- Log into your GitHub account
- Click on 'Repositories' at top
- Click on 'New' at top-right
- Click on 'Import a repository' link at top
- For URL, enter: https://github.com/1to9only/HoDoKu
- For your Repository Name, enter: HoDoKu
- [or any other name you wish]
- You can make your repository Public or Private
- Click on 'Begin import'
- Done.

**To fork a copy of my HoDoKu into your own repository**:
- Log into your GitHub account
- Switch to: https://github.com/1to9only/HoDoKu
- Click on 'Fork' at top-right
- Done.

**Comment by CCV54** [comment]
@1to9only Thank you for the info. I've saved it as a PDF, for future reference, as per your helpful instruction on another discussion.

Now I can see the Dark version in action, some of what you were saying about it makes more sense to me. It looks much better in your screen shot with the dark blue/cyan title bar (R:G:B 36:64:86 according to the GIMP) and white text. On my machine it's white(ish) with black text, presumably from System Default. ? I had some fun back in the day when you could change colours and fonts/font size/colour for various display elements, such as Title bar, but those days are long gone. Apart from that, I don't immediately see any colour changes required. Yes, as you suggest, the puzzle board itself could be changed to more suit the dark mode, and I might like to experiment with that. However, some colours can't be changed from within the program. There's the 'white' border around the Sudoku board, for one thing, and the b'ground colours in View > Summary, Solution Path etc.. set by L&F.  The nearest to anything suitably dark, in that area, is CDE/Motif, but I suspect making changes of that order way beyond me.

The filter numbers for Dark mode, on the other hand, do need some attention. The active numbers reduced in opacity is easy, but it looks, to me, like the inactive numbers need some more serious attention. Not only do they appear about a pixel below the actives, in this case, (another fairly easy fix) but they don't work as intended against such a dark b'ground. Added transparency might be some help here too, but I'd be inclined to build some flatter versions to go with the general flat look.
On that topic as well, I'd be looking to make flat (and maybe darker) undo/redo images and, more especially, Hint Buttons.
Could be a while off tho, more than one rainy day.

Meanwhile, all credit and due regard to you for your input into this project. I most certainly couldn't have done it without you!
It has been a great help to me personally, but, more importantly, I think, a step toward improving what was already a wonderful program. Hopefully there will be some further contributions, now it has been possible in this way. Idk.. Maybe even some additional solving techniques. ?

Until then, then.

**Comment by 1to9only** [comment]
In Windows 10:

To display your own images as Desktop backgrounds:
Settings -> Personalization -> Background -> Slideshow -> Pick a folder with your images

Additional customization:
Settings -> Personalization -> Colors -> Enable the checkboxes

**Comment by CCV54** [comment]
Oh, I see.. Add accent colour to title bar etc.. Didn't notice that before, or if I did my chosen accent colour accent colour doesn't look good there.

Cheers.

**Comment by CCV54** [comment]
Minor update:
The installer.exe you use doesn't result in HoDoKu showing up in Windows Apps & Features, nor in IObit Uninstaller. I did navigate to the program files folder for 2.2.1, and used the Uninstall.exe there, before installing 2.2.2. Otoh, there does appear to an Uninstall option available by right-click on the Start Menu. Haven't tested that....

Still curious about how hobiwan packaged it. All I can see is that his installer as a .msi file, instead of .exe.
